name: Build
on:
  push:
    paths-ignore:
      - "README.md"
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - run: make
